ecommerce_project/cart_app/urls.py
from django.urls import pathfrom . import viewsapp_name='cart_app'urlpatterns = [    path('add/<int:product_id>/',views.add_cart,name='add_cart'),    path('', views.cart_detail, name='cart_detail'),    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),]

ecommerce_project/ecommerce_app/urls.py
from django.urls import pathfrom . import viewsapp_name = 'ecommerce_app'urlpatterns = [    path('', views.allProCat,name='allProCat'),    path('<slug:slug>/', views.allProCat,name='products_by_category'),    path('<slug:c_slug>/<slug:product_slug>/', views.productDetails,name='proCatdetail'),]

ecommerce_project/ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerce_app/', include('ecommerce_app.urls')),
    path('search/', include('search_app.urls')),
    path('cart_app/', include('cart_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerce_project/search_app/urls.py
from django.urls import pathfrom . import viewsapp_name = 'search_app'urlpatterns = [    path('', views.SearchResult, name='SearchResult'),]

ecommerce_project/cart_app/models.py
from django.db import models
from ecommerce_app.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
     product=models.ForeignKey(Product,on_delete=models.CASCADE)
     cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
     quantity=models.IntegerField()
     active=models.BooleanField(default=True)

     class Meta:
          db_table='CartItem'
     def sub_total(self):
          return self.product.price*self.quantity
     def __str__(self):
          return '{}'.format(self.product)

ecommerce_project/ecommerce_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
     name=models.CharField(max_length=250,unique=True)
     slug=models.SlugField(max_length=250,unique=True)
     description=models.TextField(blank=True)
     image=models.ImageField(upload_to='category',blank=True)

     class Meta:
         ordering=('name',)
         verbose_name='category'
         verbose_name_plural='categories'
     def get_url(self):
          return reverse('ecommerce_app:products_by_category',args=[self.slug])
     def __str__(self):
         return '{}'.format(self.name)

class Product(models.Model):
     name=models.CharField(max_length=250,unique=True)
     slug=models.SlugField(max_length=250,unique=True)
     description=models.TextField(blank=True)
     price=models.DecimalField(max_digits=10,decimal_places=2)
     category=models.ForeignKey(Category,on_delete=models.CASCADE)
     image=models.ImageField(upload_to='product',blank=True)
     stock=models.IntegerField()
     available=models.BooleanField(default=True)
     created=models.DateTimeField(auto_now_add=True)
     updated=models.DateTimeField(auto_now=True)

     def get_url(self):
         return reverse('ecommerce_app:proCatdetail',args=[self.category.slug,self.slug])

     class Meta:
         ordering=('name',)
         verbose_name='product'
         verbose_name_plural='products'
     def __str__(self):
         return '{}'.format(self.name)

ecommerce_project/search_app/models.py
from django.db import models

# Create your models here.

ecommerce_project/cart_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecommerce_app.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart_app:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity >1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_app:cart_detail')
def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart_app:cart_detail')

ecommerce_project/ecommerce_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.http import HttpResponse
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.

def allProCat(request,slug=None):
    c_page=None
    products_list=None
    if slug:
        c_page=get_object_or_404(Category,slug=slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request, 'category.html',{'category':c_page,'products':products})

def productDetails(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecommerce_project/search_app/views.py
from django.shortcuts import render
from ecommerce_app.models import Product
from django.db.models import Q
# Create your views here.
def SearchResult(request):
     products=None
     query=None
     if 'q' in request.GET:
          query=request.GET.get('q')
          products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
          return render(request,'search.html',{'query':query,'products':products})

ecommerce_project/templates/base.html
{% load static %}<!DOCTYPE html><html lang="en"><head>    <meta charset="UTF-8">    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@200&display=swap" rel="stylesheet">    <script src="https://kit.fontawesome.com/b5f31f706a.js" crossorigin="anonymous"></script>    <link rel="stylesheet" href="{% static 'css/custom.css' %}">    <meta name="description" content="{% block metadescription %}{% endblock %}">    <meta name="viewport" content="width=device-width, initial-scale=1">    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"">    <title>{% block title %}{% endblock %}</title></head><body><div>{% include 'header.html' %}{% include 'nav.html' %}{% block content %}{% endblock %}</div>{% include 'footer.html' %}<script src="{% static 'js/popper.min.js' %}"></script><script src="{% static 'js/bootstrap.min.js' %}"></script><script src="{% static 'css/custom.css' %}"></script></body></html>

ecommerce_project/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">    <p class="text-center">&copy; ABC Shop pvt ltd .All rights Reserved</p></div>

ecommerce_project/templates/header.html
{% load static %}<header>    <center>        <a href="{% url 'ecommerce_app:allProCat' %}"><img src="{% static 'img/logo.png' %}" alt="LogoImage" style="width:250px;height:170px;"></a>    </center></header>

ecommerce_project/templates/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary ">  <div class="container-fluid">    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">      <span class="navbar-toggler-icon"></span>    </button>    <div class="collapse navbar-collapse" id="navbarSupportedContent">      <ul class="navbar-nav me-auto mb-2 mb-lg-0">        <li class="nav-item">          <a class="nav-link" href="{% url 'ecommerce_app:allProCat' %}">Home</a>        </li>        <li class="nav-item dropdown {% if 'ecommerce_app' in request.path %}active{% endif %}">          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">            All Category          </a>          <ul class="dropdown-menu">            <li><a class="dropdown-item" href="{% url 'ecommerce_app:allProCat' %}"></a></li>              {% for category in links %}            <li><a class="dropdown-item" href="{{category.get_url}}">{{category.name}}</a></li>            <li><hr class="dropdown-divider"></li>              {% endfor %}          </ul>        </li>        {% if item_count > 0 %}        <li class="nav-item">          <a class="nav-link" href="{% url 'cart_app:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i> Cart({{item_count}})</a>        </li>        {% endif %}      </ul>      <form class="d-flex" role="search" action="{% url 'search_app:SearchResult' %}" method="get">        {% csrf_token %}        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search" >        <button class="btn btn-outline-primary" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>      </form>    </div>  </div></nav>

ecommerce_project/templates/product.html
{% extends 'base.html' %}{% load static %}{% block metadescription %}        {{product.description|truncatewords:155}}{% endblock %}{% block title %}    {% if category %}        {{product.name}} - ABC Tech    {% endif %}{% endblock %}{% block content %}        <div class="row my_pro_row_class">            <div class="mx_auto">                <p><a href="{% url 'ecommerce_app:allProCat' %}">Home</a> | <a href="{{product.get_url}}">{{product.category}}</a>{{product.name}}</p>            </div>        </div><div class="container"><br><div class="row" style="padding-bottom:10px ">    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">        <div style="min-width:18rem;">            <img src="{{product.image.url}}" alt="{{product.name }} image" width="400" height="300" class="product_image">        </div>    </div>        <div class="col-12 col-sm-12 col-md-12 col-lg-6">            <h1 class="my_prod_title">{{product.name}}</h1>            <p>${{product.price}}</p>            <p class="my_title">Product description</p>            <p class="text-justify my_prod_text">{{product.description}}</p>            {% if product.stock <= 0 %}            <p class="text-justify my_prod_text"><b>Out of Stock</b></p>            {% else %}            <a class="btn btn-success" href="{% url 'cart_app:add_cart' product.id %}">Add to cart</a>            {% endif %}        </div>    </div></div>{% endblock %}

ecommerce_project/templates/search.html
{% extends 'base.html' %}{% load static %}{% block metadescription %}   We have variety of products.{% endblock %}{% block title %}   Search{% endblock %}{% block content %}   <div>      <p class="text-center my_search_text"> You have searched for <b>"{{query}}"</b> </p>   </div>   <div class="container">    <div class="row mx_auto">        {% for product in products %}            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">                <div class="card text-center" style="min-width:18rem;">                    <a href="{{product.get_url}}"><img class="card-img-top my_img" src="{{product.image.url}}"  alt="{{product.name}}"></a>                    <div class="card-body">                        <h4>{{product.name}}</h4>                        <p>{{product.price}}</p>                    </div>                </div>            </div>       {% empty %}       <div class="row mx_auto">           <p class="text-center my_search_text">0 results found</p>       </div>       {% endfor %}       </div>      </div>{% endblock %}